[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Filament_Competitive_RRAM"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["software_simulation"]
